name: Update Visitor Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:      # Allows manual trigger for testing

jobs:
  update-stats:
    permissions:
      contents: write    # Add permission to push to repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./resume
        run: npm install

      - name: Convert and Update Stats
        run: |
          node ./resume/src/utils/processData.js ./resume/src/assets/data-export.csv

      - name: Commit and Push to main
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add ./resume/src/assets/visitor-stats.json
          git commit -m "Update visitor stats" || exit 0
          git push origin main

      - name: Deploy to GitHub Pages
        working-directory: ./resume
        env:
          GIT_USER: github-actions[bot]
          # GIT_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npx gh-pages -d dist --cname cheedge.leeindeutschland.de --repo https://x-access-token:${GITHUB_TOKEN}@github.com/cheedge/cheedge.github.io.git
#  echo "cheedge.leeindeutschland.de" > dist/CNAME
